### ISSUE TITLE
Potential issue when updating auth from refresh token

### ISSUE THREAD

**Issue by BenJeau** [BenJeau/currently_playing_spotify#3]
After running it for a few days/week on my server, it broke and the following error was shown (it's either something on my end or Spotify - error deserializing via serde)

```sh
INFO currently_playing_spotify::auth: Querying Spotify access token auth API
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 2, column: 1) }', src/auth.rs:111:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

Should probably handle the Option instead of unwrapping https://github.com/BenJeau/currently_playing_spotify/blob/main/src/auth.rs#L111

**Comment by BenJeau** [comment]
This has just happened again - I will push an update that properly handles the option

**Comment by BenJeau** [comment]
Version `0.1.4` now prints more debug logs when this error will happen and will print the body of the response.

Have a hunch that it may simply be related to the token being invalid or hitting a rate-limit.

**Comment by BenJeau** [comment]
Different error

```rust
2022-04-12T16:31:56.148717Z  INFO currently_playing_spotify::auth: Querying Spotify currently playing track API
2022-04-12T16:31:56.225530Z  INFO currently_playing_spotify::auth: User NOT currently playing music
2022-04-12T16:31:57.149255Z  INFO currently_playing_spotify::auth: Querying Spotify access token auth API
thread 'tokio-runtime-worker' panicked at 'Error parsing body. Error: Error("missing field `access_token`", line: 1, column: 58). Body: "{\"error\":\"temporarily_unavailable\",\"error_description\":\"\"}"', src/auth.rs:116:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```
